-- MySQL Script generated by MySQL Workbench
-- 07/27/14 16:46:01
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hbdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hbdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `hbdb` ;

-- -----------------------------------------------------
-- Table `hbdb`.`malData`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hbdb`.`malData` (
  `hbID` INT NOT NULL,
  `title` VARCHAR(80) NULL,
  `english_title` VARCHAR(80) NULL,
  `romaji_title` VARCHAR(80) NULL,
  `episodes` INT NULL,
  `status` INT NULL,
  `startdate` DATETIME NULL,
  `enddate` DATETIME NULL,
  `image` VARCHAR(140) NULL,
  `synopsis` VARCHAR(5000) NULL,
  `type` VARCHAR(10) NULL,
  PRIMARY KEY (`hbID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hbdb`.`watching`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hbdb`.`watching` (
  `hbID` INT NULL,
  `Folder` VARCHAR(80) NULL,
  `PrefTitle` VARCHAR(80) NULL,
  `Progress` INT NULL,
  INDEX `fk_airing_malData1_idx` (`malID` ASC),
  CONSTRAINT `fk_airing_malData1`
    FOREIGN KEY (`malID`)
    REFERENCES `hbdb`.`malData` (`hbID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hbdb`.`archived`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hbdb`.`archived` (
  `hbID` INT NULL,
  `Folder` VARCHAR(80) NULL,
  `PrefTitle` VARCHAR(80) NULL,
  INDEX `fk_archived_malData_idx` (`malID` ASC),
  CONSTRAINT `fk_archived_malData`
    FOREIGN KEY (`malID`)
    REFERENCES `hbdb`.`malData` (`hbID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hbdb`.`subgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hbdb`.`subgroups` (
  `groupID` INT NOT NULL,
  `groupName` VARCHAR(45) NULL,
  `isJoint` TINYINT(1) NULL,
  `priority` SMALLINT NULL,
  `website` VARCHAR(80) NULL,
  PRIMARY KEY (`groupID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hbdb`.`anime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hbdb`.`episodes` (
  `hbID` INT NULL,
  `episode_number` INT NULL,
  `v` INT NULL,
  `date_aired` DATETIME NULL,
  `date_downloaded` DATETIME NULL,
  `groupID` INT NULL,
  `isBD` TINYINT(1) NULL,
  `CRC` CHAR(8) NULL,
  `epName` VARCHAR(80) NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
